site_name: Momoa
repo_url:
site_description: A library for definition, validation and serialisation of models based on JSONSchema specifications.
site_author: Berislav Lopac <berislav@lopac.net>
use_directory_urls: false
theme:
  name: readthedocs
extra_css:
  - css/custom.css
plugins:
  - search
  - mkapi
markdown_extensions:
  - toc:
      permalink: yes
  - codehilite:
      guess_lang: no
nav:
  - index.md
  - reference.md
