site_name: Momoa
repo_url: https://github.com/berislavlopac/momoa
site_url: https://momoa.readthedocs.io
site_description: A library for definition, validation and serialization of models based on JSONSchema specifications.
site_author: Berislav Lopac <berislav@lopac.net>
use_directory_urls: false
theme:
  name: material
  favicon: assets/code-json.svg
  icon:
    logo: material/code-json
plugins:
  - mkapi
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - index.md
  - API Reference: mkapi/api/momoa
