[tool.poetry]
name = "momoa"
version = "0.1.1"
description = "A library for definition, validation and serialisation of Python objects based on JSONSchema specifications."
authors = ["Berislav Lopac <berislav@lopac.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://momoa.readthedocs.io"
repository = "https://github.com/berislavlopac/momoa"
packages = [
    { include = "momoa/" },
]

[tool.poetry.dependencies]
python = "^3.8"
statham-schema = "^0.13.5"
stringcase = "^1.2.0"
python-dateutil = "^2.8.2"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.1.2"
pytest-cov = ">=3.0.0"
black = ">=22.1.0"
isort = ">=5.10.1"
mypy = ">=0.931"
pytest-spec = ">=3.2.0"
flake8 = ">=4.0.1"
pydocstyle = ">=6.1.1"
toml = ">=0.10.2"
mutmut = ">=2.4.0"
tox = ">=3.25.0"
tox-poetry = ">=0.4.1"

[tool.poetry.group.docs.dependencies]
mkdocs = ">=1.3.0"
mkdocs-material = ">=8.5.6"

[tool.black]
line-length = 100
target-version = ['py38', 'py39']
verbose = false
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
filter_files = true
force_alphabetical_sort_within_sections = true

[tool.coverage.run]
source = [ "momoa/", ]
omit = [ "*/tests/*", "src/tests/*", ]

[tool.coverage.report]
skip_covered = false
show_missing = true
fail_under = 90
exclude_lines = [ "pragma: no cover", "@abstract",]

[tool.mypy]
mypy_path = "momoa/"
ignore_missing_imports = true

[tool.pydocstyle]
add-ignore = "D105, D107, D212, D401"
convention = "google"
match-dir = "(?!tests).*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
